version: "3.3"

services:
  api:
    image: "docker.kvacek.cz/poletani/api:latest"
    command: "uvicorn src.asgi:app --port=8000 --host=0.0.0.0 --workers 4"
    network_mode: "host"
    restart: "always"
    env_file:
      - .env
    environment:
      SENTRY_DSN: "https://184d1d6bd39f4fbb94804ae84e9afdd5@o472821.ingest.sentry.io/5506983"
    volumes:
      - ./uploads:/app/uploads
