services:
  db:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=ull_tracker
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql:rw
  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      TZ: "Europe/Prague"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./config/nginx.dev.yml:/etc/nginx/conf.d/app-dev.conf
      - ./uploads:/app/uploads
    ports:
      - "8999:8999"
volumes:
  db-data: { }