services:
  db:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=ull_tracker
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql:rw
  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      TZ: "Europe/Prague"
      API_URL: "http://localhost:8000"
      APP_ENV: "development"
      ALLOW_CORS_ORIGINS: "http://localhost:9000 http://localhost:9001"
      SENTRY_DSN: "https://184d1d6bd39f4fbb94804ae84e9afdd5@o472821.ingest.sentry.io/5506983"


  scrapy:
    build:
      context: ../crawlers
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=ull_tracker
      - MYSQL_HOST=db
    volumes:
      - db-data:/var/lib/mysql:rw
      - ../crawlers:/app

volumes:
  db-data: { }