"""password len

Revision ID: 19ce22e5926b
Revises: de421195d45c
Create Date: 2023-05-06 21:01:42.983935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19ce22e5926b'
down_revision = 'de421195d45c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hashed',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hashed',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    # ### end Alembic commands ###
