"""add datetime to weather_info

Revision ID: 2a320e1e093d
Revises: 36ea098fde31
Create Date: 2023-08-01 04:47:22.122423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a320e1e093d'
down_revision = '36ea098fde31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_info', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_info', 'datetime')
    # ### end Alembic commands ###
