"""add is_public to flight

Revision ID: 300b721e0818
Revises: 707eb800ddcd
Create Date: 2023-08-08 22:08:34.559165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300b721e0818'
down_revision = '707eb800ddcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'is_public')
    # ### end Alembic commands ###
