"""add icon and description to poi type and description to poi

Revision ID: 76752a74a304
Revises: 5c43394aa8e0
Create Date: 2023-08-23 11:08:44.313882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76752a74a304'
down_revision = '5c43394aa8e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_of_interest', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('point_of_interest_type', sa.Column('icon', sa.String(length=128), server_default='marker', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_of_interest_type', 'icon')
    op.drop_column('point_of_interest', 'description')
    # ### end Alembic commands ###
