"""zmena v gps, pridani poi_id do photo

Revision ID: ef51b2cd596a
Revises: 7304ac2f580b
Create Date: 2023-06-29 08:21:24.755261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef51b2cd596a'
down_revision = '7304ac2f580b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('airport', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.drop_column('airport', 'gps_position')
    op.add_column('flight_track', sa.Column('point_of_interest_id', sa.Integer(), nullable=False))
    op.drop_constraint('flight_track_ibfk_2', 'flight_track', type_='foreignkey')
    op.create_foreign_key(None, 'flight_track', 'point_of_interest', ['point_of_interest_id'], ['id'])
    op.drop_column('flight_track', 'poi_id')
    op.add_column('photo', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('photo', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('photo', sa.Column('poin_of_interest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'point_of_interest', ['poin_of_interest_id'], ['id'])
    op.drop_column('photo', 'gps_position')
    op.add_column('point_of_interest', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('point_of_interest', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.drop_column('point_of_interest', 'gps_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_of_interest', sa.Column('gps_position', sa.NullType(), nullable=True))
    op.drop_column('point_of_interest', 'gps_longitude')
    op.drop_column('point_of_interest', 'gps_latitude')
    op.add_column('photo', sa.Column('gps_position', sa.NullType(), nullable=True))
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'poin_of_interest_id')
    op.drop_column('photo', 'gps_longitude')
    op.drop_column('photo', 'gps_latitude')
    op.add_column('flight_track', sa.Column('poi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flight_track', type_='foreignkey')
    op.create_foreign_key('flight_track_ibfk_2', 'flight_track', 'point_of_interest', ['poi_id'], ['id'])
    op.drop_column('flight_track', 'point_of_interest_id')
    op.add_column('airport', sa.Column('gps_position', sa.NullType(), nullable=True))
    op.drop_column('airport', 'gps_longitude')
    op.drop_column('airport', 'gps_latitude')
    # ### end Alembic commands ###
