"""add seats to aircraft

Revision ID: 71d100e65f04
Revises: dd48d8dab743
Create Date: 2023-08-16 06:46:02.618843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71d100e65f04'
down_revision = 'dd48d8dab743'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'seats')
    # ### end Alembic commands ###
