"""aircraft photo

Revision ID: 431adcd37681
Revises: 8491bd15ab4a
Create Date: 2023-05-31 20:18:02.644970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431adcd37681'
down_revision = '8491bd15ab4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('photo_filename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'photo_filename')
    # ### end Alembic commands ###
