"""add photos to aircraft, poi and copilots

Revision ID: 91a9608b509d
Revises: d42172840f6c
Create Date: 2023-11-28 16:32:56.725312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a9608b509d'
down_revision = 'd42172840f6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_has_photo',
    sa.Column('copilot_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('copilot_id', 'photo_id')
    )
    op.add_column('aircraft', sa.Column('title_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aircraft', 'photo', ['title_photo_id'], ['id'])
    op.add_column('flight', sa.Column('title_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flight', 'photo', ['title_photo_id'], ['id'])
    op.add_column('photo', sa.Column('aircraft_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'aircraft', ['aircraft_id'], ['id'])
    op.add_column('point_of_interest', sa.Column('title_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'point_of_interest', 'photo', ['title_photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point_of_interest', type_='foreignkey')
    op.drop_column('point_of_interest', 'title_photo_id')
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'aircraft_id')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'title_photo_id')
    op.drop_constraint(None, 'aircraft', type_='foreignkey')
    op.drop_column('aircraft', 'title_photo_id')
    op.drop_table('copilot_has_photo')
    # ### end Alembic commands ###
