"""uprava cover photo u letu, aircraft.call_sign

Revision ID: f19757a615cc
Revises: 7dc6dd7d0f59
Create Date: 2023-06-29 16:03:51.185228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f19757a615cc'
down_revision = '7dc6dd7d0f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('call_sign', sa.String(length=16), nullable=False))
    op.drop_column('aircraft', 'name')
    op.drop_constraint('flight_ibfk_6', 'flight', type_='foreignkey')
    op.drop_column('flight', 'cover_photo_id')
    op.add_column('photo', sa.Column('is_flight_cover', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'is_flight_cover')
    op.add_column('flight', sa.Column('cover_photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('flight_ibfk_6', 'flight', 'photo', ['cover_photo_id'], ['id'])
    op.add_column('aircraft', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('aircraft', 'call_sign')
    # ### end Alembic commands ###
