"""add title photo url for user

Revision ID: b1bd8ecc3251
Revises: b5c66e5a2df7
Create Date: 2023-08-08 19:08:13.021213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bd8ecc3251'
down_revision = 'b5c66e5a2df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title_image_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title_image_url')
    # ### end Alembic commands ###
