"""add crop info

Revision ID: c3aef4ae2669
Revises: 2acb6fa61028
Create Date: 2023-10-20 23:53:21.772545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aef4ae2669'
down_revision = '2acb6fa61028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_adjustment', sa.Column('crop_left', sa.Float(), nullable=True))
    op.add_column('photo_adjustment', sa.Column('crop_top', sa.Float(), nullable=True))
    op.add_column('photo_adjustment', sa.Column('crop_width', sa.Float(), nullable=True))
    op.add_column('photo_adjustment', sa.Column('crop_height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_adjustment', 'crop_height')
    op.drop_column('photo_adjustment', 'crop_width')
    op.drop_column('photo_adjustment', 'crop_top')
    op.drop_column('photo_adjustment', 'crop_left')
    # ### end Alembic commands ###
