"""add soft delete

Revision ID: fd5fc5c1e2f6
Revises: 5781b1432475
Create Date: 2023-06-06 05:00:23.250817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5fc5c1e2f6'
down_revision = '5781b1432475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('flight', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('metar', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('organization', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'deleted')
    op.drop_column('metar', 'deleted')
    op.drop_column('flight', 'deleted')
    op.drop_column('copilot', 'deleted')
    # ### end Alembic commands ###
