"""add soft delete

Revision ID: 559795b043f3
Revises: fd5fc5c1e2f6
Create Date: 2023-06-06 05:00:51.512887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559795b043f3'
down_revision = 'fd5fc5c1e2f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('point_of_interest', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('point_of_interest_type', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_of_interest_type', 'deleted')
    op.drop_column('point_of_interest', 'deleted')
    op.drop_column('airport', 'deleted')
    # ### end Alembic commands ###
