"""add terrain elevation to photos and event table

Revision ID: 6e5cc5123a2b
Revises: 76752a74a304
Create Date: 2023-09-05 09:54:45.509461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5cc5123a2b'
down_revision = '76752a74a304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('flight', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('flight', sa.Column('has_terrain_elevation', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'flight', 'event', ['event_id'], ['id'])
    op.add_column('photo', sa.Column('terrain_elevation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'terrain_elevation')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'has_terrain_elevation')
    op.drop_column('flight', 'event_id')
    op.drop_table('event')
    # ### end Alembic commands ###
