"""edit

Revision ID: 8491bd15ab4a
Revises: d15debffedf8
Create Date: 2023-05-23 05:47:26.866008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8491bd15ab4a'
down_revision = 'd15debffedf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'deleted')
    # ### end Alembic commands ###
