"""edit

Revision ID: d15debffedf8
Revises: 7951a7b79007
Create Date: 2023-05-23 05:42:29.097139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd15debffedf8'
down_revision = '7951a7b79007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('manufacturer', sa.Text(), server_default='', nullable=False))
    op.add_column('aircraft', sa.Column('model', sa.String(length=30), nullable=False))
    op.drop_column('aircraft', 'type')
    op.alter_column('user', 'avatar_image_url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_image_url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.add_column('aircraft', sa.Column('type', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('aircraft', 'model')
    op.drop_column('aircraft', 'manufacturer')
    # ### end Alembic commands ###
