"""photo.gps_altitude

Revision ID: cf1fb904e9ab
Revises: 708fc32f6a3b
Create Date: 2023-07-31 08:57:10.715298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1fb904e9ab'
down_revision = '708fc32f6a3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('gps_altitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'gps_altitude')
    # ### end Alembic commands ###
