"""rename from/to in events

Revision ID: 8b0c020dc0c4
Revises: 39a62618eacb
Create Date: 2023-09-22 08:53:20.901142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b0c020dc0c4'
down_revision = '39a62618eacb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_from', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('date_to', sa.DateTime(), nullable=True))
    op.drop_column('event', 'event_from')
    op.drop_column('event', 'event_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_to', mysql.DATETIME(), nullable=True))
    op.add_column('event', sa.Column('event_from', mysql.DATETIME(), nullable=True))
    op.drop_column('event', 'date_to')
    op.drop_column('event', 'date_from')
    # ### end Alembic commands ###
