"""add title photo to copilot

Revision ID: 022bf6fbcd47
Revises: e5682ac4355c
Create Date: 2023-12-02 13:05:46.267006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022bf6fbcd47'
down_revision = 'e5682ac4355c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot', sa.Column('title_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'copilot', 'photo', ['title_photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copilot', type_='foreignkey')
    op.drop_column('copilot', 'title_photo_id')
    # ### end Alembic commands ###
