"""flight cover photo

Revision ID: 7304ac2f580b
Revises: 419cf23cbf83
Create Date: 2023-06-29 07:35:54.303608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7304ac2f580b'
down_revision = '419cf23cbf83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('cover_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flight', 'photo', ['cover_photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'cover_photo_id')
    # ### end Alembic commands ###
