"""flight edit

Revision ID: 5781b1432475
Revises: 66e39f31b1d2
Create Date: 2023-06-06 04:35:10.408586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5781b1432475'
down_revision = '66e39f31b1d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('solo', sa.Boolean(), nullable=False))
    op.add_column('flight', sa.Column('with_instructor', sa.Boolean(), nullable=False))
    op.add_column('flight', sa.Column('landings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'landings')
    op.drop_column('flight', 'with_instructor')
    op.drop_column('flight', 'solo')
    # ### end Alembic commands ###
