"""avatar url

Revision ID: 7951a7b79007
Revises: 19ce22e5926b
Create Date: 2023-05-07 21:42:58.261939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7951a7b79007'
down_revision = '19ce22e5926b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image_url', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_image_url')
    # ### end Alembic commands ###
